name: Auto-assign PR author

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
jobs:
  assign:
    uses: devfellowship/dfl-ci/.github/workflows/auto-assign.yml@main
    secrets: inherit
